import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;

public class ClientUI extends javax.swing.JFrame {

    Client client;

    /**
     * Creates new form ClientUI
     */
    public ClientUI() {
        initComponents();
        spnPort.setValue(1500);
        spnPort.setEnabled(true);
        btnAddFile.setEnabled(false);
        btnDownload.setEnabled(false);
        btnSearch.setEnabled(false);
        btnLogout.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfUsername = new javax.swing.JTextField();
        txfServerIP = new javax.swing.JTextField();
        spnPort = new javax.swing.JSpinner();
        btnConnect = new javax.swing.JButton();
        btnAddFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaFileList = new javax.swing.JTextArea();
        txfSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cmbSearchResults = new javax.swing.JComboBox<>();
        btnDownload = new javax.swing.JButton();
        txfActivity = new javax.swing.JTextField();
        progressBarDown = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        progressBarUp = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        btnDownPause = new javax.swing.JButton();
        btnUpPause = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(441, 598));
        setMinimumSize(new java.awt.Dimension(441, 598));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(99, 99, 99));
        jPanel1.setMaximumSize(new java.awt.Dimension(441, 598));
        jPanel1.setMinimumSize(new java.awt.Dimension(441, 598));
        jPanel1.setPreferredSize(new java.awt.Dimension(441, 598));

        jPanel2.setBackground(new java.awt.Color(63, 63, 63));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("P2P File Sharing");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel4)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Username");

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Server IP");

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Server port");

        txfUsername.setBackground(new java.awt.Color(123, 123, 123));
        txfUsername.setForeground(java.awt.Color.white);
        txfUsername.setText("R");
        txfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfUsernameActionPerformed(evt);
            }
        });
        txfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfUsernameKeyPressed(evt);
            }
        });

        txfServerIP.setBackground(new java.awt.Color(123, 123, 123));
        txfServerIP.setForeground(java.awt.Color.white);
        txfServerIP.setText("localhost");
        txfServerIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfServerIPActionPerformed(evt);
            }
        });
        txfServerIP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfServerIPKeyPressed(evt);
            }
        });

        spnPort.setModel(new javax.swing.SpinnerNumberModel(1000, 1000, null, 1));

        btnConnect.setBackground(new java.awt.Color(76, 76, 76));
        btnConnect.setForeground(java.awt.Color.white);
        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        btnAddFile.setBackground(new java.awt.Color(76, 76, 76));
        btnAddFile.setForeground(java.awt.Color.white);
        btnAddFile.setText("Add file");
        btnAddFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFileActionPerformed(evt);
            }
        });

        txaFileList.setEditable(false);
        txaFileList.setBackground(new java.awt.Color(123, 123, 123));
        txaFileList.setColumns(20);
        txaFileList.setForeground(java.awt.Color.white);
        txaFileList.setRows(5);
        jScrollPane1.setViewportView(txaFileList);

        txfSearch.setBackground(new java.awt.Color(123, 123, 123));
        txfSearch.setForeground(java.awt.Color.white);
        txfSearch.setToolTipText("To search all files, leave this field empty.");

        btnSearch.setBackground(new java.awt.Color(76, 76, 76));
        btnSearch.setForeground(java.awt.Color.white);
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        cmbSearchResults.setBackground(new java.awt.Color(66, 66, 66));
        cmbSearchResults.setForeground(java.awt.Color.white);

        btnDownload.setBackground(new java.awt.Color(76, 76, 76));
        btnDownload.setForeground(java.awt.Color.white);
        btnDownload.setText("Download");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        txfActivity.setEditable(false);
        txfActivity.setBackground(new java.awt.Color(123, 123, 123));
        txfActivity.setForeground(java.awt.Color.white);

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Download Progress");

        progressBarUp.setName(""); // NOI18N

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Upload Progress");

        btnDownPause.setBackground(new java.awt.Color(76, 76, 76));
        btnDownPause.setForeground(java.awt.Color.white);
        btnDownPause.setText("Pause");
        btnDownPause.setEnabled(false);
        btnDownPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownPauseActionPerformed(evt);
            }
        });

        btnUpPause.setBackground(new java.awt.Color(76, 76, 76));
        btnUpPause.setForeground(java.awt.Color.white);
        btnUpPause.setText("Pause");
        btnUpPause.setEnabled(false);
        btnUpPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpPauseActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(76, 76, 76));
        btnLogout.setForeground(java.awt.Color.white);
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfActivity, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbSearchResults, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txfSearch))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDownload, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(progressBarDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(progressBarUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnDownPause, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                            .addComponent(btnUpPause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txfServerIP, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spnPort, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnConnect)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(211, 211, 211))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txfServerIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConnect)
                    .addComponent(btnLogout))
                .addGap(18, 18, 18)
                .addComponent(txfActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddFile, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbSearchResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDownload))
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDownPause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressBarDown, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpPause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressBarUp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUsernameActionPerformed

    }//GEN-LAST:event_txfUsernameActionPerformed

    private void txfServerIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfServerIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfServerIPActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        connect();
    }//GEN-LAST:event_btnConnectActionPerformed

    public void connect() {
        String username = txfUsername.getText().trim();
        String serverIP = txfServerIP.getText().trim();
        int serverPort = (int) spnPort.getValue();
        if (username.equals("")) {
            txfActivity.setText("Please enter a username.");
        } else if (serverIP.equals("")) {
            txfActivity.setText("Please enter a server address.");
        } else {
            client = new Client(serverIP, serverPort, username);
            if (!client.start()) {
                //txaClientOut.setText(" *** Error starting client *** \n");
                txfActivity.setText("Error starting client.");
            } else if (client.readStartMessage()) {
                client.startListeningFromServer();
                txfActivity.setText("Successfully connected.");
                btnConnect.setEnabled(false);
                txfServerIP.setEditable(false);
                txfUsername.setEditable(false);
                spnPort.setEnabled(false);
                btnAddFile.setEnabled(true);
                btnDownload.setEnabled(false);
                btnSearch.setEnabled(true);
                btnLogout.setEnabled(true);
                //btnUpPause.setEnabled(true);
                //btnDownPause.setEnabled(true);
            } else {
                txfActivity.setText("This username is not available.");
                txfUsername.setText("");
            }

        }
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        close();
    }//GEN-LAST:event_formWindowClosing

    private void btnAddFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFileActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(null);
        File f = fileChooser.getSelectedFile();

        try {
            String filePath = f.getAbsolutePath();
            String[] split = filePath.split("/");
            String fileName = split[split.length - 1];
            client.addFile(new FileEntry(filePath, fileName));

            txaFileList.append(filePath + "\n");
            System.out.println(filePath);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnAddFileActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        client.clearResults();
        String fileSearch = txfSearch.getText().trim();
        Message m = new Message(Message.SEARCH);
        m.setUsername(client.getUsername());
        m.setMesssage(fileSearch);
        client.sendMessage(m);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        String[] split = ((String) cmbSearchResults.getSelectedItem()).split(": ");
        Message m = new Message(Message.REQUESTDOWNLOAD);
        m.setMesssage(split[1]);
        m.setUsername(split[0]);
        m.setUsername2(client.getUsername());
        double randomKey = Math.random();
        m.setRandomKey(randomKey);
        client.setCurRandomKey(randomKey);
        System.out.println("Random key: " + randomKey);
        client.generateKeyPairs();
        m.setPublicKey(client.getPublicKey());
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setDialogTitle("Choose a folder where to save the file.");
        fileChooser.setAcceptAllFileFilterUsed(false);
        String filePath = "./";
        progressBarDown.setValue(0);
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = fileChooser.getSelectedFile();
            filePath = f.getAbsolutePath();
            client.sendMessage(m);
            client.setDestFilePath(filePath + "/" + m.getMessage());
        } else {
            System.out.println("No Selection ");
        }
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        logout();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnDownPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownPauseActionPerformed
        if (client.isDownPause()) {
            client.setDownPause(false);
            btnDownPause.setText("Pause");
        } else {
            client.setDownPause(true);
            btnDownPause.setText("Resume");
        }
    }//GEN-LAST:event_btnDownPauseActionPerformed

    private void btnUpPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpPauseActionPerformed
        if (client.isUpPause()) {
            client.setUpPause(false);
            btnUpPause.setText("Pause");
        } else {
            client.setUpPause(true);
            btnUpPause.setText("Resume");
        }
    }//GEN-LAST:event_btnUpPauseActionPerformed

    private void txfUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfUsernameKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            connect();
        }
    }//GEN-LAST:event_txfUsernameKeyPressed

    private void txfServerIPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfServerIPKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            connect();
        }
    }//GEN-LAST:event_txfServerIPKeyPressed

    public static void updateList(ArrayList<String> list) {
        cmbSearchResults.setModel(new DefaultComboBoxModel(list.toArray()));
        if (list.size() > 0) {
            btnDownload.setEnabled(true);
        } else {
            btnDownload.setEnabled(false);
        }

    }

    private void close() {
        try {
            client.stopListeningFromServer();
            client.disconnect();

        } catch (NullPointerException e) {

        }
        setVisible(false);
        dispose();
        System.exit(0);
    }

    private void logout() {
        client.disconnect();
        client.stopListeningFromServer();
        client = null;
        txaFileList.setText("");
        btnConnect.setEnabled(true);
        txfUsername.setEditable(true);
        spnPort.setEnabled(true);
        txfServerIP.setEnabled(true);
        btnAddFile.setEnabled(false);
        btnDownload.setEnabled(false);
        btnSearch.setEnabled(false);
        btnLogout.setEnabled(false);
        btnUpPause.setEnabled(false);
        btnDownPause.setEnabled(false);
        progressBarDown.setValue(0);
        progressBarUp.setValue(0);
        txfActivity.setText("Successfully logged out.");

    }

    public static void displayToClient(String s) {
        txfActivity.setText(s);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFile;
    private javax.swing.JButton btnConnect;
    public static javax.swing.JButton btnDownPause;
    public static javax.swing.JButton btnDownload;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearch;
    public static javax.swing.JButton btnUpPause;
    public static javax.swing.JComboBox<String> cmbSearchResults;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JProgressBar progressBarDown;
    public static javax.swing.JProgressBar progressBarUp;
    private javax.swing.JSpinner spnPort;
    private javax.swing.JTextArea txaFileList;
    private static javax.swing.JTextField txfActivity;
    private javax.swing.JTextField txfSearch;
    private javax.swing.JTextField txfServerIP;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
